INFRA_ANALYZER_AGENT = "infra-analyzer"
DEPENDENCY_ANALYZER_AGENT = "dependency-analyzer"


INFRA_ANALYZER_PLUGIN_NAME = "InfraAnalyzer"
DEPENDENCY_ANALYZER_PLUGIN_NAME = "DependencyAnalyzer"

DEPENDENCY_ANALYSIS_COMPLETE = "DEPENDENCY_ANALYSIS_COMPLETE"
